"""empty message

Revision ID: 0a536f64decc
Revises: 970fed0c6e0d
Create Date: 2018-05-19 09:45:58.962000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a536f64decc'
down_revision = '970fed0c6e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentrecord', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentrecord', 'status')
    # ### end Alembic commands ###
