"""empty message

Revision ID: 71d6ed8d11a7
Revises: 90891d160fcb
Create Date: 2018-05-14 19:56:36.151000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d6ed8d11a7'
down_revision = '90891d160fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('community', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
