"""empty message

Revision ID: 77210c4f7079
Revises: 
Create Date: 2018-05-08 16:10:32.401000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77210c4f7079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('mantel', sa.String(length=11), nullable=False),
    sa.Column('manname', sa.String(length=10), nullable=False),
    sa.Column('manpsw', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('mantel')
    )
    op.create_table('user',
    sa.Column('usertel', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('userpsw', sa.String(length=10), nullable=False),
    sa.Column('usersex', sa.Boolean(), nullable=False),
    sa.Column('userage', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(length=30), nullable=True),
    sa.Column('useravatar', sa.String(length=100), nullable=True),
    sa.Column('userjob', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('usertel')
    )
    op.create_table('house',
    sa.Column('houseID', sa.String(length=20), nullable=False),
    sa.Column('housetitle', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('community', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('lng', sa.String(length=30), nullable=False),
    sa.Column('lat', sa.String(length=30), nullable=False),
    sa.Column('housepic', sa.String(length=200), nullable=False),
    sa.Column('housearea', sa.Float(), nullable=False),
    sa.Column('housedirect', sa.String(length=5), nullable=False),
    sa.Column('housefloor', sa.String(length=5), nullable=False),
    sa.Column('househall', sa.String(length=10), nullable=False),
    sa.Column('balcony', sa.Boolean(), nullable=False),
    sa.Column('bathroom', sa.Boolean(), nullable=False),
    sa.Column('housestatus', sa.Boolean(), nullable=False),
    sa.Column('housetype', sa.String(length=5), nullable=False),
    sa.Column('housearound', sa.Text(), nullable=True),
    sa.Column('ownertel', sa.String(length=11), nullable=False),
    sa.Column('mantel', sa.String(length=11), nullable=False),
    sa.Column('tenanttel', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['mantel'], ['manager.mantel'], ),
    sa.ForeignKeyConstraint(['tenanttel'], ['user.usertel'], ),
    sa.PrimaryKeyConstraint('houseID')
    )
    op.create_table('housepic',
    sa.Column('picID', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=200), nullable=False),
    sa.Column('houseID', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['houseID'], ['house.houseID'], ),
    sa.PrimaryKeyConstraint('picID')
    )
    op.create_table('payment',
    sa.Column('payID', sa.Integer(), nullable=False),
    sa.Column('payname', sa.String(length=10), nullable=False),
    sa.Column('payrent', sa.Integer(), nullable=False),
    sa.Column('paydeposit', sa.Integer(), nullable=False),
    sa.Column('payservice', sa.Integer(), nullable=False),
    sa.Column('houseID', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['houseID'], ['house.houseID'], ),
    sa.PrimaryKeyConstraint('payID')
    )
    op.create_table('rentrecord',
    sa.Column('reID', sa.Integer(), nullable=False),
    sa.Column('retime', sa.Date(), nullable=False),
    sa.Column('repayment', sa.String(length=10), nullable=False),
    sa.Column('rerent', sa.Integer(), nullable=False),
    sa.Column('redeposit', sa.Integer(), nullable=False),
    sa.Column('reservice', sa.Integer(), nullable=False),
    sa.Column('checkin', sa.Date(), nullable=False),
    sa.Column('checkout', sa.Date(), nullable=False),
    sa.Column('usertel', sa.String(length=11), nullable=False),
    sa.Column('managertel', sa.String(length=11), nullable=False),
    sa.Column('houseID', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['houseID'], ['house.houseID'], ),
    sa.ForeignKeyConstraint(['managertel'], ['manager.mantel'], ),
    sa.ForeignKeyConstraint(['usertel'], ['user.usertel'], ),
    sa.PrimaryKeyConstraint('reID')
    )
    op.create_table('userrecord',
    sa.Column('ureID', sa.Integer(), nullable=False),
    sa.Column('uretype', sa.String(length=10), nullable=False),
    sa.Column('timeapply', sa.Date(), nullable=True),
    sa.Column('timedeal', sa.Date(), nullable=True),
    sa.Column('timeend', sa.Date(), nullable=True),
    sa.Column('urestatus', sa.String(length=10), nullable=False),
    sa.Column('usertel', sa.String(length=11), nullable=False),
    sa.Column('houseID', sa.String(length=20), nullable=False),
    sa.Column('managertel', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['houseID'], ['house.houseID'], ),
    sa.ForeignKeyConstraint(['managertel'], ['manager.mantel'], ),
    sa.ForeignKeyConstraint(['usertel'], ['user.usertel'], ),
    sa.PrimaryKeyConstraint('ureID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userrecord')
    op.drop_table('rentrecord')
    op.drop_table('payment')
    op.drop_table('housepic')
    op.drop_table('house')
    op.drop_table('user')
    op.drop_table('manager')
    # ### end Alembic commands ###
