"""empty message

Revision ID: 90891d160fcb
Revises: 77210c4f7079
Create Date: 2018-05-14 19:37:21.128000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90891d160fcb'
down_revision = '77210c4f7079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'ownertel')
    op.drop_constraint(u'rentrecord_ibfk_2', 'rentrecord', type_='foreignkey')
    op.drop_column('rentrecord', 'managertel')
    op.drop_constraint(u'userrecord_ibfk_2', 'userrecord', type_='foreignkey')
    op.drop_column('userrecord', 'managertel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrecord', sa.Column('managertel', mysql.VARCHAR(length=11), nullable=False))
    op.create_foreign_key(u'userrecord_ibfk_2', 'userrecord', 'manager', ['managertel'], ['mantel'])
    op.add_column('rentrecord', sa.Column('managertel', mysql.VARCHAR(length=11), nullable=False))
    op.create_foreign_key(u'rentrecord_ibfk_2', 'rentrecord', 'manager', ['managertel'], ['mantel'])
    op.add_column('house', sa.Column('ownertel', mysql.VARCHAR(length=11), nullable=False))
    # ### end Alembic commands ###
